import { Platform, StyleSheet } from "react-native";

const displayFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif-condensed",
  default: "System",
});

const textFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif",
  default: "System",
});

export const getDietSetupStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: 50,
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    topBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
    },
    rightActions: {
      alignItems: "flex-end",
      gap: 8,
    },
    exitEditButton: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    exitEditText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    headerTitle: {
      color: colors.text,
      fontSize: 30,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    stepBadge: {
      backgroundColor: colors.surface,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    stepBadgeText: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: textFont,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 16,
    },
    introText: {
      color: colors.text,
      fontSize: 15,
      textAlign: "center",
      lineHeight: 23,
      marginBottom: 14,
      fontFamily: textFont,
    },
    optionsList: {
      gap: 12,
      marginBottom: 14,
    },
    optionCard: {
      backgroundColor: colors.background,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingVertical: 14,
      gap: 8,
    },
    optionCardActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "12",
    },
    optionIcon: {
      width: 58,
      height: 58,
      borderRadius: 29,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignSelf: "center",
    },
    optionTitle: {
      color: colors.text,
      fontSize: 18,
      textAlign: "center",
      fontWeight: "700",
      fontFamily: displayFont,
    },
    optionDescription: {
      color: colors.textSecondary,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
      fontFamily: textFont,
    },
    fieldGroup: {
      gap: 10,
      marginBottom: 12,
    },
    genderChoices: {
      flexDirection: "row",
      gap: 12,
    },
    genderChoice: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      minHeight: 58,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    genderChoiceActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "14",
    },
    genderChoiceText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    fieldLabel: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "700",
      fontFamily: textFont,
    },
    fieldRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.accent + "66",
      borderRadius: 16,
      paddingHorizontal: 16,
      minHeight: 56,
      gap: 10,
    },
    input: {
      flex: 1,
      color: colors.text,
      fontSize: 21,
      fontFamily: textFont,
    },
    unitText: {
      color: colors.accent,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    infoBox: {
      flexDirection: "row",
      gap: 10,
      backgroundColor: colors.accent + "22",
      borderWidth: 1,
      borderColor: colors.accent + "66",
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
      alignItems: "center",
    },
    infoText: {
      color: colors.text,
      flex: 1,
      fontSize: 14,
      lineHeight: 20,
      fontFamily: textFont,
    },
    bottomButton: {
      marginTop: "auto",
      backgroundColor: colors.accent,
      borderRadius: 40,
      height: 56,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    bottomButtonDisabled: {
      opacity: 0.5,
    },
    bottomButtonText: {
      color: colors.background,
      fontSize: 18,
      fontWeight: "700",
      fontFamily: textFont,
    },
    simpleChoices: {
      gap: 12,
      marginBottom: 16,
    },
    simpleChoice: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 16,
      paddingHorizontal: 14,
    },
    simpleChoiceActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "14",
    },
    simpleChoiceText: {
      color: colors.text,
      textAlign: "center",
      fontSize: 15,
      fontWeight: "600",
      fontFamily: textFont,
    },
  // Step 3 – Meal schedule
  mealList: {
    gap: 10,
    marginBottom: 10,
  },
  mealItem: {
    backgroundColor: colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  mealIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  mealContent: {
    flex: 1,
    gap: 10,
  },
  mealTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    fontFamily: textFont,
  },
  mealTimeButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.accent + "55",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mealTimeText: {
    color: colors.text,
    fontSize: 15,
    fontFamily: textFont,
  },
});
