import { Dimensions, Platform, StyleSheet } from "react-native";

const { width: screenWidth } = Dimensions.get("window");

const displayFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif-condensed",
  default: "System",
});

const textFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif",
  default: "System",
});

export const getDietSetupStyles = (colors: any) => {
  const scale = Math.min(1.25, Math.max(0.8, screenWidth / 390));
  const s = (v: number) => Math.round(v * scale);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: s(50),
      paddingHorizontal: s(20),
      paddingBottom: s(20),
    },
    topBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      gap: s(10),
    },
    backButton: {
      width: s(48),
      height: s(48),
      borderRadius: s(24),
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    headerTitle: {
      color: colors.text,
      fontSize: s(30),
      fontWeight: "700",
      fontFamily: displayFont,
      flex: 1,
      textAlign: "center",
      paddingHorizontal: s(4),
    },
    stepBadge: {
      backgroundColor: colors.surface,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      maxWidth: "38%",
      minWidth: s(102),
      flexShrink: 0,
    },
    stepBadgeText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: "700",
      fontFamily: textFont,
      textAlign: "center",
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      flex: 1,
    },
    savedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.accent + "44",
      backgroundColor: colors.accent + "12",
      marginBottom: 12,
    },
    savedBadgeText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "600",
      fontFamily: textFont,
    },
    introText: {
      color: colors.text,
      fontSize: 16,
      textAlign: "center",
      lineHeight: 26,
      marginBottom: 20,
      fontFamily: textFont,
    },
    optionsList: {
      gap: 16,
      marginBottom: 20,
    },
    optionCard: {
      backgroundColor: colors.background,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 20,
      gap: 12,
    },
    optionCardActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "12",
    },
    optionIcon: {
      width: s(68),
      height: s(68),
      borderRadius: s(34),
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignSelf: "center",
    },
    optionTitle: {
      color: colors.text,
      fontSize: s(34),
      textAlign: "center",
      fontWeight: "700",
      fontFamily: displayFont,
    },
    optionDescription: {
      color: colors.textSecondary,
      fontSize: s(15),
      textAlign: "center",
      lineHeight: s(24),
      fontFamily: textFont,
    },
    fieldGroup: {
      gap: 10,
      marginBottom: 18,
    },
    labelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    helpButton: {
      width: s(26),
      height: s(26),
      borderRadius: s(13),
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.accent + "12",
    },
    genderChoices: {
      flexDirection: "row",
      gap: 12,
    },
    genderChoice: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: s(8),
      minHeight: s(58),
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: s(16),
      paddingHorizontal: s(14),
      paddingVertical: s(12),
    },
    genderChoiceActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "14",
    },
    genderChoiceText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    fieldLabel: {
      color: colors.text,
      fontSize: 17,
      fontWeight: "700",
      fontFamily: textFont,
    },
    exampleHint: {
      color: colors.textSecondary,
      fontSize: 13,
      borderRadius: 10,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      paddingVertical: 6,
      fontFamily: textFont,
    },
    fieldRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.accent + "66",
      borderRadius: s(16),
      paddingHorizontal: s(16),
      height: s(64),
      gap: s(10),
    },
    input: {
      flex: 1,
      color: colors.text,
      fontSize: s(20),
      fontFamily: textFont,
    },
    unitText: {
      color: colors.accent,
      fontSize: s(20),
      fontWeight: "700",
      fontFamily: textFont,
    },
    infoBox: {
      flexDirection: "row",
      gap: s(10),
      backgroundColor: colors.accent + "22",
      borderWidth: 1,
      borderColor: colors.accent + "66",
      borderRadius: s(14),
      padding: s(14),
      marginBottom: s(20),
      alignItems: "center",
    },
    infoText: {
      color: colors.text,
      flex: 1,
      fontSize: s(15),
      lineHeight: s(22),
      fontFamily: textFont,
    },
    activityList: {
      gap: 8,
    },
    activityOption: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    activityOptionActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "12",
    },
    activityTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "700",
      fontFamily: textFont,
    },
    activitySubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: textFont,
    },
    bottomButton: {
      marginTop: "auto",
      backgroundColor: colors.accent,
      borderRadius: s(40),
      height: s(64),
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: s(8),
    },
    bottomButtonDisabled: {
      opacity: 0.5,
    },
    bottomButtonText: {
      color: colors.background,
      fontSize: s(20),
      fontWeight: "700",
      fontFamily: textFont,
    },
    simpleChoices: {
      gap: 12,
      marginBottom: 16,
    },
    simpleChoice: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 16,
      paddingHorizontal: 14,
    },
    simpleChoiceActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "14",
    },
    simpleChoiceText: {
      color: colors.text,
      textAlign: "center",
      fontSize: 15,
      fontWeight: "600",
      fontFamily: textFont,
    },
    // Step 3 – Meal schedule
    mealList: {
      gap: 14,
      marginBottom: 14,
    },
    mealItem: {
      backgroundColor: colors.background,
      borderRadius: s(16),
      borderWidth: 1,
      borderColor: colors.border,
      padding: s(16),
      flexDirection: "row",
      alignItems: "flex-start",
      gap: s(14),
    },
    mealIcon: {
      width: s(46),
      height: s(46),
      borderRadius: s(23),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    mealContent: {
      flex: 1,
      gap: 10,
    },
    mealTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    mealTimeButton: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.accent + "55",
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    mealTimeText: {
      color: colors.text,
      fontSize: 16,
      fontFamily: textFont,
    },
    mealToggleRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    mealToggleText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      fontFamily: textFont,
    },
  });
};
