// app/index.styles.ts
import { Dimensions, Platform, StyleSheet } from "react-native";

const { width: screenWidth } = Dimensions.get("window");

const displayFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif-condensed",
  default: "System",
});

const textFont = Platform.select({
  ios: "Avenir Next",
  android: "sans-serif",
  default: "System",
});

export const getIndexStyles = (colors: any) => {
  const scale = Math.min(1.25, Math.max(0.8, screenWidth / 390));
  const s = (v: number) => Math.round(v * scale);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: s(50),
      paddingHorizontal: s(20),
      paddingBottom: s(20),
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: s(40),
      height: s(40),
      borderRadius: s(20),
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
    },
    headerTitleContainer: {
      alignItems: "center",
      flex: 1,
    },
    headerTitle: {
      color: colors.text,
      fontSize: s(24),
      fontWeight: "700",
      fontFamily: displayFont,
    },
    stepIndicator: {
      backgroundColor: colors.surface,
      color: colors.accent,
      paddingHorizontal: s(12),
      paddingVertical: s(4),
      borderRadius: s(20),
      fontSize: s(12),
      fontWeight: "600",
      marginTop: s(5),
      fontFamily: textFont,
    },
    addButton: {
      width: s(40),
      height: s(40),
      borderRadius: s(20),
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
    },
    tabsContainer: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 50,
      padding: 4,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.accent + "1A",
    },
    tab: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: s(8),
      paddingVertical: s(12),
      borderRadius: s(50),
    },
    activeTab: {
      backgroundColor: colors.accent,
    },
    tabText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      fontFamily: textFont,
    },
    activeTabText: {
      color: colors.background,
    },
    summaryContainer: {
      backgroundColor: colors.surface,
      borderRadius: s(16),
      padding: s(20),
      marginBottom: s(20),
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.accent + "1A",
    },
    summaryItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    summaryIcon: {
      width: s(40),
      height: s(40),
      borderRadius: s(20),
      justifyContent: "center",
      alignItems: "center",
    },
    summaryIconActive: {
      backgroundColor: colors.accent,
    },
    summaryIconTotal: {
      backgroundColor: "#4CAF50",
    },
    summaryLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "500",
      fontFamily: textFont,
    },
    summaryValue: {
      color: colors.text,
      fontSize: s(24),
      fontWeight: "700",
      fontFamily: displayFont,
    },
    summaryDivider: {
      width: 1,
      height: 40,
      backgroundColor: colors.border,
    },
    listContent: {
      paddingBottom: 20,
    },
    alarmCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      marginBottom: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    alarmCardActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "08",
    },
    alarmCardInactive: {
      borderColor: colors.border,
    },
    alarmTimeContainer: {
      marginBottom: 15,
    },
    alarmTimeHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: s(10),
    },
    alarmTime: {
      fontSize: s(28),
      fontWeight: "700",
      letterSpacing: 0.5,
      fontFamily: displayFont,
    },
    alarmTimeActive: {
      color: colors.accent,
    },
    alarmTimeInactive: {
      color: colors.textSecondary,
    },
    alarmStatus: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    alarmStatusActive: {
      backgroundColor: "rgba(76, 175, 80, 0.2)",
    },
    alarmStatusInactive: {
      backgroundColor: "rgba(244, 67, 54, 0.2)",
    },
    alarmStatusText: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.text,
      fontFamily: textFont,
    },
    alarmDetails: {
      gap: 6,
    },
    alarmName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: textFont,
    },
    alarmDaysText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    descriptionContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    alarmDescription: {
      color: colors.textSecondary,
      fontSize: 14,
      flex: 1,
      fontFamily: textFont,
    },
    alarmControls: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 15,
    },
    switchContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    switchLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "500",
      fontFamily: textFont,
    },
    deleteButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(244, 67, 54, 0.1)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    editAlarmButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      marginHorizontal: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 40,
      marginTop: 40,
    },
    emptyIconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.accent + "1A",
    },
    emptyStateTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "700",
      marginBottom: 10,
      textAlign: "center",
      fontFamily: displayFont,
    },
    emptyStateText: {
      color: colors.textSecondary,
      fontSize: 16,
      textAlign: "center",
      marginBottom: 25,
      lineHeight: 22,
      fontFamily: textFont,
    },
    emptyStateButton: {
      backgroundColor: colors.accent,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      paddingHorizontal: 25,
      paddingVertical: 15,
      borderRadius: 50,
    },
    emptyStateButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    // Diet Tab Styles
    dietContent: {
      paddingBottom: 100,
    },
    dietHeader: {
      marginBottom: 20,
    },
    dietHeaderTitle: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 8,
    },
    dietHeaderText: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    dietDate: {
      color: colors.textSecondary,
      fontSize: 14,
      fontFamily: textFont,
    },
    streakCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.accent + "1A",
    },
    streakInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    streakIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.accent + "1A",
      justifyContent: "center",
      alignItems: "center",
    },
    streakLabel: {
      color: colors.textSecondary,
      fontSize: 15,
      fontWeight: "700",
      fontFamily: textFont,
    },
    streakValue: {
      color: colors.accent,
      fontSize: 28,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    editButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    sectionCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.accent + "1A",
    },
    sectionTitle: {
      color: colors.accent,
      fontSize: 18,
      fontWeight: "700",
      marginBottom: 15,
      fontFamily: displayFont,
    },
    chartHeader: {
      marginBottom: 10,
    },
    chartSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      fontFamily: textFont,
    },
    lineChart: {
      marginVertical: 16,
      alignSelf: "center",
      borderRadius: 16,
    },
    progressChart: {
      marginVertical: 16,
      alignSelf: "center",
      borderRadius: 16,
    },
    progressChartContainer: {
      alignItems: "center",
      marginBottom: 20,
    },
    progressStats: {
      gap: 12,
    },
    progressStat: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    statDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    statLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      width: 70,
      fontFamily: textFont,
    },
    statValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      flex: 1,
      fontFamily: textFont,
    },
    chartStats: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 10,
    },
    chartStat: {
      color: colors.text,
      fontSize: 14,
      fontFamily: textFont,
    },
    chartStatLabel: {
      color: colors.textSecondary,
    },
    chartStatValue: {
      color: colors.accent,
      fontWeight: "600",
      fontFamily: textFont,
    },
    quickControls: {
      gap: 20,
      marginBottom: 20,
    },
    quickControl: {
      gap: 10,
    },
    controlLabel: {
      color: colors.text,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: textFont,
    },
    controlButtons: {
      flexDirection: "row",
      gap: 12,
    },
    controlButton: {
      flex: 1,
      backgroundColor: colors.border,
      padding: 12,
      borderRadius: 10,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    controlButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      fontFamily: textFont,
    },
    detailButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      padding: 16,
      backgroundColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    detailButtonText: {
      color: colors.accent,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: textFont,
    },
    tipCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      flexDirection: "row",
      gap: 15,
      borderWidth: 1,
      borderColor: colors.accent + "1A",
      marginBottom: 20,
    },
    tipIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.accent + "1A",
      justifyContent: "center",
      alignItems: "center",
    },
    tipContent: {
      flex: 1,
    },
    tipTitle: {
      color: colors.accent,
      fontSize: 16,
      fontWeight: "700",
      marginBottom: 5,
      fontFamily: displayFont,
    },
    tipText: {
      color: colors.text,
      fontSize: 14,
      lineHeight: 20,
      fontFamily: textFont,
    },
    // Diet Onboarding Styles
    onboardingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 30,
    },
    onboardingContent: {
      alignItems: "center",
      gap: 30,
    },
    onboardingLogo: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.accent,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    onboardingTitle: {
      color: colors.text,
      fontSize: 32,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    onboardingSubtitle: {
      color: colors.textSecondary,
      fontSize: 16,
      textAlign: "center",
      fontFamily: textFont,
    },
    onboardingBox: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 24,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    onboardingBoxGreeting: {
      color: colors.accent,
      fontSize: 28,
      fontWeight: "700",
      textAlign: "center",
      fontFamily: displayFont,
    },
    onboardingBoxText: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 24,
      textAlign: "center",
      fontFamily: textFont,
    },
    onboardingStartButton: {
      backgroundColor: colors.accent,
      paddingVertical: 16,
      paddingHorizontal: 40,
      borderRadius: 50,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    onboardingStartButtonText: {
      color: colors.background,
      fontSize: 18,
      fontWeight: "700",
      fontFamily: textFont,
    },
    onboardingOptions: {
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
      marginTop: 20,
      gap: 15,
    },
    onboardingOption: {
      alignItems: "center",
      flex: 1,
      gap: 8,
    },
    onboardingOptionIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    onboardingOptionLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
      fontFamily: textFont,
    },
    dietHeroCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 22,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.accent + "26",
      gap: 10,
    },
    dietHeroBadge: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      gap: 8,
      backgroundColor: colors.accent + "14",
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    dietHeroBadgeText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    dietHeroTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    dietHeroText: {
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      fontFamily: textFont,
    },
    dietMetricsRow: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 18,
    },
    dietMetricCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    dietMetricLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.6,
      fontFamily: textFont,
    },
    dietMetricValue: {
      color: colors.text,
      fontSize: s(34),
      fontWeight: "700",
      fontFamily: displayFont,
    },
    dietMetricValueSmall: {
      color: colors.text,
      fontSize: s(20),
      fontWeight: "700",
      fontFamily: displayFont,
    },
    dietMetricHint: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "600",
      fontFamily: textFont,
    },
    metricActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 2,
      alignSelf: "flex-start",
    },
    metricActionText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    caloriesValue: {
      color: colors.accent,
      fontSize: s(36),
      fontWeight: "700",
      marginBottom: s(4),
      fontFamily: displayFont,
    },
    caloriesCaption: {
      color: colors.textSecondary,
      fontSize: 13,
      marginBottom: 12,
      fontFamily: textFont,
    },
    caloriesDescription: {
      color: colors.text,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 16,
      fontFamily: textFont,
    },
    caloriesBreakdownRow: {
      flexDirection: "row",
      gap: 12,
    },
    macrosRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 14,
    },
    macroCard: {
      flex: 1,
      borderRadius: 12,
      padding: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    macroLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: "700",
      marginBottom: 6,
      fontFamily: textFont,
    },
    macroValue: {
      fontSize: 20,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    macroCarbsCard: {
      borderColor: "#1976D2",
      backgroundColor: "rgba(25, 118, 210, 0.08)",
    },
    macroCarbsValue: {
      color: "#0D47A1",
    },
    macroProteinCard: {
      borderColor: "#D32F2F",
      backgroundColor: "rgba(211, 47, 47, 0.08)",
    },
    macroProteinValue: {
      color: "#B71C1C",
    },
    macroFatsCard: {
      borderColor: "#F9A825",
      backgroundColor: "rgba(249, 168, 37, 0.12)",
    },
    macroFatsValue: {
      color: "#E65100",
    },
    caloriesBreakdownCard: {
      flex: 1,
      backgroundColor: colors.background,
      borderRadius: s(16),
      padding: s(14),
      borderWidth: 1,
      borderColor: colors.border,
      gap: s(6),
    },
    caloriesBreakdownLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "600",
      fontFamily: textFont,
    },
    caloriesBreakdownValue: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "700",
      fontFamily: displayFont,
    },
    dietDetailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: s(16),
      paddingVertical: s(12),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    dietDetailLabel: {
      color: colors.textSecondary,
      fontSize: s(14),
      flex: 1,
      fontFamily: textFont,
    },
    dietDetailValue: {
      color: colors.text,
      fontSize: s(14),
      fontWeight: "700",
      textAlign: "right",
      flexShrink: 1,
      fontFamily: textFont,
    },
    dietEditButton: {
      backgroundColor: colors.accent,
      borderRadius: 999,
      paddingVertical: 16,
      paddingHorizontal: 22,
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    dietEditButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: "700",
      fontFamily: textFont,
    },
    dailyStatusText: {
      color: colors.text,
      fontSize: 14,
      lineHeight: 21,
      marginBottom: 14,
      fontFamily: textFont,
    },
    dailyInputGroup: {
      gap: 8,
      marginBottom: 12,
    },
    dailyInputLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      fontFamily: textFont,
    },
    dailyLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    helpIconButton: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.accent + "14",
    },
    dailyInputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      borderRadius: 12,
      minHeight: 48,
      paddingHorizontal: 12,
    },
    dailyInput: {
      flex: 1,
      color: colors.text,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: textFont,
    },
    dailyInputSuffix: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: textFont,
    },
    dailyStatusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginTop: 2,
      marginBottom: 12,
    },
    dailyStatusBadgeSuccess: {
      backgroundColor: "rgba(76, 175, 80, 0.14)",
      borderWidth: 1,
      borderColor: "rgba(76, 175, 80, 0.35)",
    },
    dailyStatusBadgePending: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dailyStatusBadgeText: {
      color: colors.text,
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      fontFamily: textFont,
    },
    emptyMealLogText: {
      color: colors.textSecondary,
      fontSize: 14,
      fontFamily: textFont,
    },
    mealLogList: {
      gap: 10,
      marginTop: 2,
    },
    mealLogRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    mealLogInfo: {
      flex: 1,
      gap: 2,
    },
    mealLogTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      fontFamily: textFont,
    },
    mealLogDays: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: textFont,
    },
    mealLogStatus: {
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderWidth: 1,
      minWidth: 92,
      alignItems: "center",
    },
    mealLogStatusActive: {
      backgroundColor: "rgba(76, 175, 80, 0.14)",
      borderColor: "rgba(76, 175, 80, 0.35)",
    },
    mealLogStatusInactive: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    mealLogStatusText: {
      color: colors.text,
      fontSize: 11,
      fontWeight: "700",
      fontFamily: textFont,
    },
    mealLogFootnote: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 12,
      fontFamily: textFont,
    },
    nutritionSearchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      borderRadius: 12,
      minHeight: 48,
      paddingHorizontal: 12,
      marginBottom: 12,
    },
    nutritionSearchInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: "600",
      fontFamily: textFont,
    },
    nutritionActionsRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginBottom: 12,
    },
    nutritionActionButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: colors.accent,
      borderRadius: 10,
      paddingHorizontal: 12,
      minHeight: 38,
    },
    nutritionActionButtonText: {
      color: colors.background,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    customFoodFormCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 10,
      marginBottom: 12,
    },
    customFoodFormTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      fontFamily: textFont,
    },
    customFoodGridRow: {
      flexDirection: "row",
      gap: 8,
    },
    customFoodInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      minHeight: 40,
      paddingHorizontal: 10,
      color: colors.text,
      backgroundColor: colors.background,
      fontFamily: textFont,
      fontSize: 14,
    },
    customFoodInputHalf: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      minHeight: 40,
      paddingHorizontal: 10,
      color: colors.text,
      backgroundColor: colors.background,
      fontFamily: textFont,
      fontSize: 14,
    },
    nutritionCategoriesRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 12,
    },
    nutritionCategoryChip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    nutritionCategoryChipActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    nutritionCategoryText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionCategoryTextActive: {
      color: colors.background,
    },
    nutritionList: {
      gap: 10,
    },
    nutritionCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 10,
    },
    nutritionDeleteButton: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      borderWidth: 1,
      borderColor: "rgba(179,58,58,0.35)",
      borderRadius: 999,
      backgroundColor: "rgba(179,58,58,0.1)",
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    nutritionDeleteButtonText: {
      color: "#B33A3A",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    nutritionCardTitleBlock: {
      flex: 1,
      gap: 2,
    },
    nutritionFoodName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionServingText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: textFont,
    },
    nutritionCaloriesBadge: {
      minWidth: 64,
      borderRadius: 10,
      backgroundColor: colors.accent + "1A",
      borderWidth: 1,
      borderColor: colors.accent + "44",
      paddingVertical: 6,
      paddingHorizontal: 8,
      alignItems: "center",
    },
    nutritionCaloriesValue: {
      color: colors.accent,
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 18,
      fontFamily: displayFont,
    },
    nutritionCaloriesLabel: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionGramsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    nutritionGramsLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.3,
      fontFamily: textFont,
    },
    nutritionGramsInputWrap: {
      flexDirection: "row",
      alignItems: "center",
      minWidth: 110,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 10,
      paddingHorizontal: 10,
      minHeight: 38,
      gap: 6,
    },
    nutritionGramsInput: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      fontFamily: textFont,
    },
    nutritionGramsSuffix: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionMacrosRow: {
      flexDirection: "row",
      gap: 8,
    },
    nutritionMacroChip: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      backgroundColor: colors.surface,
      paddingVertical: 8,
      paddingHorizontal: 8,
      alignItems: "center",
      gap: 2,
    },
    nutritionMacroLabel: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.3,
      fontFamily: textFont,
    },
    nutritionMacroValue: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionEmptyState: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.background,
      paddingVertical: 14,
      paddingHorizontal: 12,
      gap: 4,
    },
    nutritionEmptyTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      fontFamily: textFont,
    },
    nutritionEmptyText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontFamily: textFont,
    },
    nutritionFootnote: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 12,
      lineHeight: 18,
      fontFamily: textFont,
    },
    historyRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    historyDayCell: {
      minWidth: 88,
      gap: 2,
    },
    historyDayText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: textFont,
    },
    historyTodayText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "700",
      fontFamily: textFont,
    },
    historyMetricsCell: {
      flex: 1,
      gap: 2,
    },
    historyMetricText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: textFont,
    },
    historyStatusChip: {
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 10,
      minWidth: 82,
      alignItems: "center",
    },
    historyStatusChipDone: {
      backgroundColor: "rgba(76, 175, 80, 0.14)",
      borderWidth: 1,
      borderColor: "rgba(76, 175, 80, 0.35)",
    },
    historyStatusChipPending: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    historyStatusChipText: {
      color: colors.text,
      fontSize: 11,
      fontWeight: "700",
      fontFamily: textFont,
    },
  });
};

// Exportamos también screenWidth por si se necesita en otros lugares
export { screenWidth };

