// app/index.styles.ts
import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

const displayFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif-condensed',
  default: 'System',
});

const textFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif',
  default: 'System',
});

export const getIndexStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleContainer: {
    alignItems: "center",
    flex: 1,
  },
  headerTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  stepIndicator: {
    backgroundColor: colors.surface,
    color: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
    fontFamily: textFont,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 50,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 50,
  },
  activeTab: {
    backgroundColor: colors.accent,
  },
  tabText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: textFont,
  },
  activeTabText: {
    color: colors.background,
  },
  summaryContainer: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  summaryItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  summaryIconActive: {
    backgroundColor: colors.accent,
  },
  summaryIconTotal: {
    backgroundColor: "#4CAF50",
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    fontFamily: textFont,
  },
  summaryValue: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  summaryDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.border,
  },
  listContent: {
    paddingBottom: 20,
  },
  alarmCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    marginBottom: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent + "08",
  },
  alarmCardInactive: {
    borderColor: colors.border,
  },
  alarmTimeContainer: {
    marginBottom: 15,
  },
  alarmTimeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  alarmTime: {
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: 0.5,
    fontFamily: displayFont,
  },
  alarmTimeActive: {
    color: colors.accent,
  },
  alarmTimeInactive: {
    color: colors.textSecondary,
  },
  alarmStatus: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  alarmStatusActive: {
    backgroundColor: "rgba(76, 175, 80, 0.2)",
  },
  alarmStatusInactive: {
    backgroundColor: "rgba(244, 67, 54, 0.2)",
  },
  alarmStatusText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.text,
    fontFamily: textFont,
  },
  alarmDetails: {
    gap: 6,
  },
  alarmName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: textFont,
  },
  descriptionContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  alarmDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    flex: 1,
    fontFamily: textFont,
  },
  alarmControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 15,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  switchLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "500",
    fontFamily: textFont,
  },
  deleteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(244, 67, 54, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  editAlarmButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    marginTop: 40,
  },
  emptyIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 10,
    textAlign: "center",
    fontFamily: displayFont,
  },
  emptyStateText: {
    color: colors.textSecondary,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 25,
    lineHeight: 22,
    fontFamily: textFont,
  },
  emptyStateButton: {
    backgroundColor: colors.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 25,
    paddingVertical: 15,
    borderRadius: 50,
  },
  emptyStateButtonText: {
    color: colors.background,
    fontSize: 16,
    fontWeight: "700",
    fontFamily: textFont,
  },
  // Diet Tab Styles
  dietContent: {
    paddingBottom: 100,
  },
  dietHeader: {
    marginBottom: 20,
  },
  dietHeaderTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  dietHeaderText: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  dietDate: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: textFont,
  },
  streakCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  streakInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  streakIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.accent + "1A",
    justifyContent: "center",
    alignItems: "center",
  },
  streakLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    fontFamily: textFont,
  },
  streakValue: {
    color: colors.accent,
    fontSize: 28,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  editButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  sectionTitle: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 15,
    fontFamily: displayFont,
  },
  chartHeader: {
    marginBottom: 10,
  },
  chartSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: textFont,
  },
  lineChart: {
    marginVertical: 16,
    alignSelf: "center",
    borderRadius: 16,
  },
  progressChart: {
    marginVertical: 16,
    alignSelf: "center",
    borderRadius: 16,
  },
  progressChartContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  progressStats: {
    gap: 12,
  },
  progressStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  statDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    width: 70,
    fontFamily: textFont,
  },
  statValue: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
    fontFamily: textFont,
  },
  chartStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  chartStat: {
    color: colors.text,
    fontSize: 14,
    fontFamily: textFont,
  },
  chartStatLabel: {
    color: colors.textSecondary,
  },
  chartStatValue: {
    color: colors.accent,
    fontWeight: "600",
    fontFamily: textFont,
  },
  quickControls: {
    gap: 20,
    marginBottom: 20,
  },
  quickControl: {
    gap: 10,
  },
  controlLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: textFont,
  },
  controlButtons: {
    flexDirection: "row",
    gap: 12,
  },
  controlButton: {
    flex: 1,
    backgroundColor: colors.border,
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  controlButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: textFont,
  },
  detailButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 16,
    backgroundColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailButtonText: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: textFont,
  },
  tipCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    gap: 15,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
    marginBottom: 20,
  },
  tipIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.accent + "1A",
    justifyContent: "center",
    alignItems: "center",
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 5,
    fontFamily: displayFont,
  },
  tipText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: textFont,
  },
});

// Exportamos también screenWidth por si se necesita en otros lugares
export { screenWidth };

