import { Platform, StyleSheet } from "react-native";

const displayFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif-condensed',
  default: 'System',
});

const textFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif',
  default: 'System',
});

export const getNewAlarmStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 50,
    paddingBottom: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 15,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleContainer: {
    alignItems: "center",
    flex: 1,
  },
  headerTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  stepIndicator: {
    backgroundColor: colors.surface,
    color: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
    fontFamily: textFont,
  },
  headerPlaceholder: {
    width: 40,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  section: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colors.accent + "1A",
  },
  sectionTitle: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    fontFamily: displayFont,
  },
  sectionDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 20,
    lineHeight: 20,
    fontFamily: textFont,
  },
  timeSelector: {
    backgroundColor: colors.background,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.border,
    marginBottom: 15,
  },
  timeIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.accent + "1A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  timeInfo: {
    flex: 1,
  },
  timeLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
    fontFamily: textFont,
  },
  timeValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "700",
    fontFamily: displayFont,
  },
  timeTip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.accent + "0D",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  timeTipText: {
    color: colors.text,
    fontSize: 14,
    flex: 1,
    fontFamily: textFont,
  },
  inputContainer: {
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    paddingVertical: 16,
    fontFamily: textFont,
  },
  charCounter: {
    color: colors.textSecondary,
    fontSize: 12,
    marginLeft: 10,
    fontFamily: textFont,
  },
  textAreaContainer: {
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
  },
  textAreaIcon: {
    position: "absolute",
    top: 16,
    left: 15,
  },
  textArea: {
    color: colors.text,
    fontSize: 16,
    paddingVertical: 16,
    paddingHorizontal: 45,
    fontFamily: textFont,
    minHeight: 120,
  },
  textAreaCounter: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: "right",
    paddingHorizontal: 15,
    paddingBottom: 10,
    fontFamily: textFont,
  },
  settingItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  settingItemLast: {
    borderBottomWidth: 0,
  },
  settingInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "500",
    fontFamily: textFont,
  },
  settingBadge: {
    backgroundColor: "rgba(76, 175, 80, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  settingBadgeText: {
    color: "#4CAF50",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: textFont,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: colors.background,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  saveButton: {
    backgroundColor: colors.accent,
    borderRadius: 50,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  saveButtonDisabled: {
    backgroundColor: colors.border,
  },
  saveButtonText: {
    color: colors.background,
    fontSize: 16,
    fontWeight: "700",
    fontFamily: textFont,
  },
});
