import { Platform, StyleSheet } from 'react-native';

const displayFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif-condensed',
  default: 'System',
});

const textFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif',
  default: 'System',
});

export const getRegistroStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      justifyContent: 'center',
      paddingHorizontal: 24,
      overflow: 'hidden',
    },
    backgroundOrbTop: {
      position: 'absolute',
      top: -90,
      left: -60,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: colors.accent + '14',
    },
    backgroundOrbBottom: {
      position: 'absolute',
      bottom: -110,
      right: -60,
      width: 250,
      height: 250,
      borderRadius: 125,
      backgroundColor: colors.accent + '0D',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
      paddingHorizontal: 2,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    headerTitleContainer: {
      alignItems: 'center',
      flex: 1,
    },
    headerTitle: {
      color: colors.text,
      fontSize: 21,
      fontWeight: '700',
      fontFamily: displayFont,
    },
    stepIndicator: {
      backgroundColor: colors.surface,
      color: colors.accent,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 20,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 5,
      fontFamily: textFont,
    },
    headerPlaceholder: {
      width: 40,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 24,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 16,
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    brandBadge: {
      alignSelf: 'center',
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: colors.accent + '18',
      borderWidth: 1,
      borderColor: colors.accent + '28',
    },
    brandBadgeText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
      fontFamily: textFont,
    },
    title: {
      fontSize: 32,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      fontFamily: displayFont,
    },
    subtitle: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 10,
      lineHeight: 22,
      fontFamily: textFont,
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 6,
      fontFamily: textFont,
    },
    input: {
      backgroundColor: colors.background + 'F2',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      color: colors.text,
      fontSize: 15,
      fontFamily: textFont,
    },
    inputError: {
      borderColor: colors.error,
    },
    errorText: {
      color: colors.error,
      fontSize: 13,
      marginTop: -2,
      fontFamily: textFont,
    },
    primaryButton: {
      marginTop: 8,
      backgroundColor: colors.accent,
      borderRadius: 16,
      paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
    },
    primaryButtonDisabled: {
      opacity: 0.6,
    },
    primaryButtonText: {
      color: colors.background,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.6,
      fontFamily: textFont,
    },
    secondaryButton: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background + 'A6',
      paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      fontFamily: textFont,
    },
  });
